In [24]:
import gzip
from netCDF4 import Dataset
import numpy as np

### Process Gauge data

In [17]:
MRMS_director = '/home/htan/proj/TensorFlow/data/MRMS/'
Guage = 'MRMS_GaugeCoor/'
Data = '20160628/'

In [18]:
filename = 'MRMS_GaugeCorr_QPE_01H_00.00_20160628-170000.nc.gz'
gz_file_path = MRMS_director + Guage + Data + filename
print(gz_file_path)

/home/htan/proj/TensorFlow/data/MRMS/MRMS_GaugeCoor/20160628/MRMS_GaugeCorr_QPE_01H_00.00_20160628-170000.nc.gz


In [22]:
outfilename = 'temp_gauge.nc'
nc_file_path = '/home/htan/proj/TensorFlow/notebook/temp/' + outfilename
print(nc_file_path)

/home/htan/proj/TensorFlow/notebook/temp/temp_gauge.nc


In [23]:
inF = gzip.open(gz_file_path, 'rb')
outF = open(nc_file_path, 'wb')
outF.write( inF.read() )
inF.close()
outF.close()

In [31]:
ncF = Dataset(nc_file_path, mode = 'r')
print ncF

<type 'netCDF4._netCDF4.Dataset'>
root group (NETCDF3_CLASSIC data model, file format NETCDF3):
    creation_date: Wed Jun 29 01:07:13 UTC 2016
    NCL_Version: 6.2.1
    system: Linux mrms-ldm 2.6.32-642.1.1.el6.x86_64 #1 SMP Tue May 31 21:57:07 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
    Conventions: None
    grib_source: MRMS_GaugeCorr_QPE_01H_00.00_20160628-170000.grib2
    title: NCL: convert-GRIB-to-netCDF
    dimensions(sizes): lat_0(3500), lon_0(7000)
    variables(dimensions): float32 VAR_209_6_9_P0_L102_GLL0(lat_0,lon_0), float32 lat_0(lat_0), float32 lon_0(lon_0)
    groups: 



In [32]:
var = ncF.variables['VAR_209_6_9_P0_L102_GLL0'][:]
lat = ncF.variables['lat_0'][:]
lon = ncF.variables['lon_0'][:]

In [33]:
var.shape, lat.shape, lon.shape

((3500, 7000), (3500,), (7000,))

In [35]:
var[:10, :10]

array([[-3., -3., -3., -3., -3., -3., -3., -3., -3., -3.],
       [-3., -3., -3., -3., -3., -3., -3., -3., -3., -3.],
       [-3., -3., -3., -3., -3., -3., -3., -3., -3., -3.],
       [-3., -3., -3., -3., -3., -3., -3., -3., -3., -3.],
       [-3., -3., -3., -3., -3., -3., -3., -3., -3., -3.],
       [-3., -3., -3., -3., -3., -3., -3., -3., -3., -3.],
       [-3., -3., -3., -3., -3., -3., -3., -3., -3., -3.],
       [-3., -3., -3., -3., -3., -3., -3., -3., -3., -3.],
       [-3., -3., -3., -3., -3., -3., -3., -3., -3., -3.],
       [-3., -3., -3., -3., -3., -3., -3., -3., -3., -3.]], dtype=float32)

In [42]:
lat[:-1:500]

array([ 54.99499893,  49.99499893,  44.99499893,  39.99499893,
        34.99499893,  29.99500084,  24.99500084], dtype=float32)

In [41]:
lon[:-1:500]

array([ 230.00500488,  235.00500488,  240.00500488,  245.00500488,
        250.00500488,  255.00500488,  260.00500488,  265.00500488,
        270.00500488,  275.00500488,  280.00500488,  285.00500488,
        290.00500488,  295.00500488], dtype=float32)

### NLDN

In [44]:
Nldn = 'MRMS_NLDN_LightningDensity/'
filename = 'MRMS_NLDN_LightningDensity_015_min_20160628-170113.nc.gz'
gz_file_path = MRMS_director + Nldn + Data + filename
print(gz_file_path)

/home/htan/proj/TensorFlow/data/MRMS/MRMS_NLDN_LightningDensity/20160628/MRMS_NLDN_LightningDensity_015_min_20160628-170113.nc.gz


In [45]:
outfilename = 'temp_NLDN.nc'
nc_file_path = '/home/htan/proj/TensorFlow/notebook/temp/' + outfilename
print(nc_file_path)

/home/htan/proj/TensorFlow/notebook/temp/temp_NLDN.nc


In [46]:
inF = gzip.open(gz_file_path, 'rb')
outF = open(nc_file_path, 'wb')
outF.write( inF.read() )
inF.close()
outF.close()

In [47]:
ncF = Dataset(nc_file_path, mode = 'r')
print ncF

<type 'netCDF4._netCDF4.Dataset'>
root group (NETCDF3_CLASSIC data model, file format NETCDF3):
    creation_date: Wed Jun 29 01:57:31 UTC 2016
    NCL_Version: 6.2.1
    system: Linux mrms-ldm 2.6.32-642.1.1.el6.x86_64 #1 SMP Tue May 31 21:57:07 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
    Conventions: None
    grib_source: MRMS_NLDN_LightningDensity_015_min_20160628-170113.grib2
    title: NCL: convert-GRIB-to-netCDF
    dimensions(sizes): lat_0(3500), lon_0(7000)
    variables(dimensions): float32 VAR_209_2_2_P0_L102_GLL0(lat_0,lon_0), float32 lat_0(lat_0), float32 lon_0(lon_0)
    groups: 



In [48]:
var = ncF.variables['VAR_209_2_2_P0_L102_GLL0'][:]
lat = ncF.variables['lat_0'][:]
lon = ncF.variables['lon_0'][:]

In [49]:
var.shape, lat.shape, lon.shape

((3500, 7000), (3500,), (7000,))

In [50]:
var[:10, :10]

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]], dtype=float32)

In [51]:
lat[:-1:500]

array([ 54.99499893,  49.99499893,  44.99499893,  39.99499893,
        34.99499893,  29.99500084,  24.99500084], dtype=float32)

In [52]:
lon[:-1:500]

array([ 230.00500488,  235.00500488,  240.00500488,  245.00500488,
        250.00500488,  255.00500488,  260.00500488,  265.00500488,
        270.00500488,  275.00500488,  280.00500488,  285.00500488,
        290.00500488,  295.00500488], dtype=float32)

In [53]:
a = {'1st':{'2nd':{'3rd':4}}}

In [56]:
a['1st']['2nd']['4th'] = 5

In [57]:
a

{'1st': {'2nd': {'3rd': 4, '4th': 5}}}

In [58]:
dir(ncF)

[u'Conventions',
 u'NCL_Version',
 '__class__',
 '__delattr__',
 '__doc__',
 '__enter__',
 '__exit__',
 '__format__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__hash__',
 '__init__',
 '__new__',
 '__orthogonal_indexing__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__unicode__',
 '_enddef',
 '_grpid',
 '_isopen',
 '_redef',
 'close',
 'cmptypes',
 'createCompoundType',
 'createDimension',
 'createEnumType',
 'createGroup',
 'createVLType',
 'createVariable',
 u'creation_date',
 'data_model',
 'delncattr',
 'dimensions',
 'disk_format',
 'enumtypes',
 'file_format',
 'filepath',
 'get_variables_by_attributes',
 'getncattr',
 u'grib_source',
 'groups',
 'isopen',
 'keepweakref',
 'ncattrs',
 'parent',
 'path',
 'renameAttribute',
 'renameDimension',
 'renameGroup',
 'renameVariable',
 'set_auto_mask',
 'set_auto_maskandscale',
 'set_auto_scale',
 'set_fill_off',
 'set_fill_on',
 'setncattr',
 'setncatts',


In [60]:
for keys in ncF.variables:
    print keys

VAR_209_2_2_P0_L102_GLL0
lat_0
lon_0


In [63]:
a = np.array([[1], [2]]).reshape(1, 2, 1)
b = np.array([[3], [4]]).reshape(1, 2, 1)

In [64]:
a.shape, b.shape

((1, 2, 1), (1, 2, 1))

In [67]:
np.dstack([a, b]).shape

(1, 2, 2)

In [68]:
import os

In [182]:
# try to implement the search function
path = '/home/htan/proj/TensorFlow/data/MRMS/MRMS_Reflectivity/20160628'

In [183]:
file_list = [f for f in os.listdir(path) if os.path.isfile(os.path.join(path, f))]

In [201]:
file_list[1].split('_20160628-')[0]

'MRMS_Reflectivity_-10C_00.50'

In [107]:
def timeToSec(time):
    if len(time) != 6:
        raise ValueError('The time formate is not correct at HHMMSS')
    hour = int(time[:2])
    minute = int(time[2:4])
    second = int(time[4:])
    return second + minute*60 + hour*3600

In [202]:
m = [[1, 2], [3, 4]]
w =np.array(m)
w.shape

(2, 2)

In [203]:
w.reshape(4,1)

array([[1],
       [2],
       [3],
       [4]])

In [204]:
w

array([[1, 2],
       [3, 4]])